### PR TITLE
Add “sponsors & partners” section to README

### PR DESCRIPTION
**Pull request by Mr0grog**
Adding a section to thank AWS and Sentry for their generous in-kind donations. Is this good? Should the name of the section be different? Am I missing orgs that should also be here?

/cc @weatherpattern @danielballan @dcwalk @titaniumbones

### CODE REVIEW

**Comment by Mr0grog** [comment]
Oops, should have CC’d you here @shapironick

**Comment by danielballan** [comment]
PageFreezer seems to be missing, and they are still floating storage costs until we can migrate their content to IA. Apologies if I’m misreading — responding on phone while on the move.

**Comment by shapironick** [comment]
+1 to PF. 

We have shout outs to AWS, Google Cloud, GSoC, Data Kind, Compute Canada, 
at the bottom of this page: https://envirodatagov.org/about/

So i think its just Page Freezer and Sentry to be added. I think @lourdesvera already started looking into adding Sentry.

**Comment by dcwalk** [comment]
+1 looks great, sorry for not responding sooner!

**Pull request merged**
