### PR TITLE
Added environmental corpus

### PR DESCRIPTION
**Pull request by ChaiBapchya**
With reference to discussion here edgi-govdata-archiving/web-monitoring-processing#21
Dataset added from EPA, wikipedia - Environmental flashwords or keywords @danielballan @dcwalk @b5 @kmcculloch @mhucka

### CODE REVIEW

**Comment by dcwalk** [comment]
@ChaiBapchya my first sense is that these preliminary corpus explorations might not be ready to be merged in immediately. I'm not sure how/where exactly they'll fit with ongoing efforts, could you expand a little bit more about how someone else will use these?

**Comment by ChaiBapchya** [comment]
Yup. So as understood from previous discussions, we need a starting point for ML training.
Before going on to creating dataset of changes, we need to first have trained dataset of Environmental corpus.
At the moment, there doesn't exist such a corpus. Hence, here's an attempt to stitch together data that is relevant to the field of Environment.
I have attached python scripts I used to collect the data.

**Comment by danielballan** [comment]
I think by 'corpus' we mean, 'set of changes with annotations indicating whether they are important or unimportant'. This looks like a word list of terms related to the environment. I can see how that could be useful, but yeah we're a long way from connecting our ongoing efforts to this. Looks useful for experimentation, not quite place-able in the codebase just yet.

**Comment by ChaiBapchya** [comment]
Alright

**Comment by dcwalk** [comment]
Are we okay to close this then @ChaiBapchya?

**Comment by ChaiBapchya** [comment]
Yes. Seems like yet another futuristic and an untimely PR.

**Pull request closed without merging**
