### PR TITLE
Add mention of meeting notes directory

### PR DESCRIPTION
**Pull request by patcon**
Related: https://github.com/edgi-govdata-archiving/web-monitoring/issues/99

### CODE REVIEW

**Comment by Mr0grog** [comment]
I think this is great; all I want is the same thing I said before and in all the other meetings: I think everyone needs to OK this so it is clear to all involved that this GDrive folder is **public.**

At least:
@weatherpattern 
@lightandluck 
@danielballan 
@trinberg 

Maybe also:
@dcwalk 
@titaniumbones

**Comment by dcwalk** [comment]
don't want to be a block! sounds good! the decision was to go with google
docs then? I thought they were gonna be PRd into the repo

**Comment by Mr0grog** [comment]
> the decision was to go with google docs then? I thought they were gonna be PRd into the repo

I think it was more like: this is where they are now, so let’s at least agree in the short term that everyone should be able to look there, rather than the current state of complete confusion. I don’t know if this is meant to be it and we’re done or not.

**Comment by weatherpattern** [comment]
@Mr0grog recollection matches mine. I already migrated everything from hackfldr to google doc. For the short term I didn't want to spend the time moving everything over again.

I'm a little concerned with the overhead of making sure that the permission settings are set to read only with link for the individual docs, after the meeting.

**Comment by dcwalk** [comment]
cool! 

Yeah @weatherpattern b/c of our nested google folders I've had that concern borne out (I think?) with the permissions shifting over time with some buries docs. Understanding what changes will effect nested docs etc... has proven fairly opaque to me at least 🤷‍♀️ 

That said -- @Mr0grog and your shared understanding: go with there it is for now, make total sense!

**Comment by patcon** [comment]
Thanks all!

**Pull request merged**
