### PR TITLE
Add code of conduct to README and CONTRIBUTING docs

### PR DESCRIPTION
**Pull request by lightandluck**
Addresses part of #111.

Wanted to make sure we were ok with the format and verbiage before copying it across the other web monitoring repos.

### CODE REVIEW

**Comment by lightandluck** [comment]
Thanks, Dan!

At today's dev meeting, Rob suggested we also ask @dcwalk take a look at this.

Dawn, can you make sure we're not missing something here?

**Comment by lightandluck** [comment]
@dcwalk Any thoughts on this? I'll merge end of day if not.

**Comment by dcwalk** [comment]
didn't realize you were waiting for me. I think this looks great!

**Comment by lightandluck** [comment]
No worries, thanks for taking a look!

In it goes 🎉

**Pull request merged**
